run_name: "symbol-detector-default"
dataset:
  coco_annotations: "../data/annotations/coco/train_annotations.json"
  images_dir: "../data/annotations/coco/images"
  classes_file: "../train/annotations/classes.yaml"
training:
  epochs: 25
  batch_size: 4
  num_workers: 4
  learning_rate: 0.0005
  lr_step_size: 8
  lr_gamma: 0.1
  weight_decay: 0.0001
  gradient_clip_norm: 5.0
  checkpoint_dir: "../models/symbols"
  checkpoint_every: 5
  resume_from: null
logging:
  use_wandb: false
  project: "sketch2bim-symbols"
  entity: null

